HootHoot_CMS/Models/QuestionType.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HootHoot_CMS.Models
{
    public class QuestionType
    {
        public QuestionType(){ }

        [Key]
        public string questiontype { get; set; }

        public ICollection<Questions> question { get; set; }


    }
}

HootHoot_CMS/Models/Questions.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace HootHoot_CMS.Models
{
    [Bind(Exclude = "station,questionType,optionType")]
    public class Questions
    {
        public Questions(){ }

        [Key]
        public int question_id { get; set; }

        [Required(ErrorMessage = "Please select the associated Station for this question.")]
        [Display (Name="Associated Station: ")]
        public string station_id { get; set; }
        
        [Required(ErrorMessage="Please enter the Question title .")]
        [Display (Name="Question:")]
        public string question_name { get; set; }

        [Required]
        [Display(Name= "Questions Type:")]
        public string question_type { get; set; }

        [Required]
        [Display(Name= "Option Type:")]
        public string option_type { get; set; }

        [Required(ErrorMessage="Please provide the FIRST option .")]
        [Display(Name = "Option 1:")]
        public string option_1 { get; set; }

        [Required(ErrorMessage = "Please provide the SECOND option .")]
        [Display(Name = "Option 2:")]
        public string option_2 { get; set; }

        [Required(ErrorMessage = "Please provide the THIRD option .")]
        [Display(Name = "Option 3:")]
        public string option_3 { get; set; }

        [Required(ErrorMessage = "Please provide the FOURTH option .")]
        [Display(Name = "Option 4:")]
        public string option_4 { get; set; }

        [Required]
        [Display(Name = "Correct Option:")]
        public string correct_option { get; set; }

        [JsonIgnore]
        [Required(ErrorMessage = "Please select whether this question has hint(s) .")]
        [Display(Name = "Are there any hints?")]
        public string question_has_hint { get; set; }

        [Required(ErrorMessage = "Please provide the hint for the question .")]
        [Display(Name = "Question Hint:")]
        public string hint { get; set; }


        [Required(ErrorMessage = "Please enter the duration of this question .")]
        [Display(Name = "Maximum time allowed to answer (seconds): ")]
        [Range(20,60,
            ErrorMessage= "Please provide the duration within the range from 20 to 60.")]
        public int answering_duration { get; set; }

        [ForeignKey("station_id")]
        [JsonIgnore]
        public Stations station { get; set; }

        [ForeignKey("question_type")]
        [JsonIgnore]
        public QuestionType questionType { get; set; }

        [ForeignKey("option_type")]
        [JsonIgnore]
        public OptionType optionType { get; set; }

        public string getsOption_Value(byte optionNo)
        {
            return getsValue_ForOption(optionNo);
        }

        private string getsValue_ForOption(byte optionNo)
        {
            if (optionNo == 1)
            {
                return option_1;
            }
            else if (optionNo == 2)
            {
                return option_2;
            }
            else if (optionNo == 3)
            {
                return option_3;
            }
            else if (optionNo == 4)
            {
                return option_4;
            }
            else
            {
                return "ERROR... INVALID Option No. Valid Option No: 1 to 4";
            }
        }

    }
}

HootHoot_CMS/Models/QuestionsViewModel.cs
namespace HootHoot_CMS.Models
{
    public class QuestionsViewModel
    {
        public string option_1 { get; set; }
        public string option_2 { get; set; }
        public string option_3 { get; set; }
        public string option_4 { get; set; }

        public void assignsOption_Value(byte optionNo, string value)
        {
            setValue_ForOption(optionNo, value);
        }

        private void setValue_ForOption(byte optionNo, string value)
        {
            if(optionNo == 1)
            {
                option_1 = value;
            }
            else if(optionNo == 2)
            {
                option_2 = value;
            }
            else if(optionNo == 3)
            {
                option_3 = value;
            }
            else if (optionNo == 4)
            {
                option_4 = value;
            }
        }
    }
}

HootHoot_CMS/Controllers/REST_API/QuestionsController.cs
using System.Collections.Generic;
using System.Web.Http;
using System.Web.Http.Cors;

using HootHoot_CMS.DAL;
using HootHoot_CMS.Models;

namespace HootHoot_CMS.Controllers.REST_API
{
    [EnableCors(origins: "*", headers: "*", methods: "GET, POST, PUT, DELETE, OPTIONS")]
    public class QuestionsController : ApiController
    {
        private QuestionsDataGateway qnsGateway = new QuestionsDataGateway();

        // GET: api/Questions
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public IEnumerable<Questions> GetQuestions()
        {
            //return db.Questions;
            return qnsGateway.SelectAll();
        }

        // GET: api/Questions/5
        /// <summary>
        /// 
        /// </summary>
        /// <param name="station_ID"></param>
        /// <returns></returns>
        public IEnumerable<Questions> GetQuestions(string station_ID)
        {
            return qnsGateway.SelectByStationID(station_ID);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

HootHoot_CMS/Controllers/View Controller/QuestionsController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;

using HootHoot_CMS.DAL;
using HootHoot_CMS.Models;
using HootHoot_CMS.Blobs;

namespace HootHoot_CMS.Controllers.View_Controller
{
    public class QuestionsController : Controller
    {
        private QuestionsDataGateway questionsGateway = new QuestionsDataGateway();
        private QuestionTypeDataGateway questionTypeGateway = new QuestionTypeDataGateway();
        private OptionTypeDataGateway optionTypeGateway = new OptionTypeDataGateway();
        private StationDataGateway stationGateway = new StationDataGateway();

        // GET: Questions
        public ActionResult Index()
        {
            //Check whether has the user logon to CMS, if the user
            // has not logon to CMS, redirect the user to the login page
            if (Session["logon_user"] == null)
            { return RedirectToAction("Login", "Accounts", new { returnUrl = Request.RawUrl }); }

            var questions = questionsGateway.SelectAll_Joint();

            assignsViewBag_FilteringResults();

            return View(questions.ToList());
        }

        [HttpPost]
        public ActionResult Index(FilterQuestionsViewModel filterQuestions)
        {
            var questions = questionsGateway.SelectAll_Joint();

            assignsViewBag_FilteringResults();

            //No need to check whether FilterQuestionsViewModel object is null, as
            //it will NEVER be null.
            string station_Filter = filterQuestions.filter_station;
            string questionType_Filter = filterQuestions.filter_questiontype;
            string optionType_Filter = filterQuestions.filter_optiontype;

            if (station_Filter != null && !station_Filter.Equals("NOFILTER"))
            {
                //Now the value of station_Filter respresents the value of the station_id
                //This is due to each item in filterStation select list holds the value of station_id
                questions = questions.Where(qns => qns.station_id == station_Filter);
            }

            if (questionType_Filter != null && !questionType_Filter.Equals("NOFILTER"))
            {
                questions = questions.Where(qns => qns.question_type == questionType_Filter);
            }

            if (optionType_Filter != null && !optionType_Filter.Equals("NOFILTER"))
            {
                questions = questions.Where(qns => qns.option_type == optionType_Filter);
            }

            return View(questions.ToList());
        }
        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            //Check whether has the user logon to CMS, if the user
            // has not logon to CMS, redirect the user to the login page
            if (Session["logon_user"] == null)
            { return RedirectToAction("Login", "Accounts", new { returnUrl = Request.RawUrl }); }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Questions questions = questionsGateway.SelectById(id);
            if (questions == null)
            {
                return HttpNotFound();
            }

            return View(questions);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            //Check whether has the user logon to CMS, if the user
            // has not logon to CMS, redirect the user to the login page
            if (Session["logon_user"] == null)
            { return RedirectToAction("Login", "Accounts", new { returnUrl = Request.RawUrl }); }

            setupImageOptions_ViewBag();
            Questions question = TempData["toSubmit_Qns"] as Questions;
            KeyValuePair<string, string>[] imageUpload_Validate = TempData["imageUpload_Validate"] as KeyValuePair<string, string>[];
            if (question !=null)
            {
                assignsViewBag_EditQuestion(question.station_id, question.question_type, question.option_type);

                if(imageUpload_Validate != null)
                {
                    for (byte i = 0; i < imageUpload_Validate.Length; i++)
                    {
                        if (!imageUpload_Validate[i].Value.Equals("PASSED"))
                        {
                            setModelState_Error(i, imageUpload_Validate[i].Value);
                        }

                    }
                }

                if (question.option_type.Equals(Constants.QNS_IMAGE_OPTION_TYPE))
                {
                    byte optionNo = 0;
                    for (byte i = 0; i < Constants.OPTIONS_PER_QNS; i++)
                    {
                        optionNo = (byte)(i + 1);
                        assignImageOptionsValue_ViewBag(optionNo, question.getsOption_Value(optionNo),
                            Constants.OPT_UPLOAD_IMAGE_STATE);
                    }
                }
                
                return View(question);
            }
            else
            {
                assignsViewBag_CreateQuestion();
                return View();
            }
            
            //return View();
        }

        // POST: Questions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Questions questions)
        {

            bool modelState_FirstPass = ModelState.IsValid; // First-Pass check of the ModelState Valid property
            bool is_ImageOptionType = false; // Initialized to false to avoid complications
            string[] listOfFiles = null;

            if (modelState_FirstPass)
            {
                is_ImageOptionType = questions.option_type == Constants.QNS_IMAGE_OPTION_TYPE;
                if (is_ImageOptionType)
                {
                    //Checks whether the specified file for each option exists in server
                    listOfFiles = new string[] { questions.option_1, questions.option_2, questions.option_3, questions.option_4 };

                    //iterate each item in listOfFiles to check whether the file exists in web server
                    for (byte i = 0; i < listOfFiles.Length; i++)
                    {
                        checkImageFileUpload_Success(i, listOfFiles[i]);

                    } // End FOR-Loop

                } // End question.option_type IF-Block

                // Do nothing if question.option_type != "IMAGE"

                if(questions.question_has_hint.Equals("NO"))
                {
                    questions.hint = "-NA-";
                }


            } // End Model.IsValid() IF-Block

            // Perform second pass ModelState check ensure that model state is still valid 
            // NOTE: This is required as it is possible for picture option type to FAIL during the first check, 
            // this has no impact to TEXT option type checks, it will still remain TRUE
            if (ModelState.IsValid)
            {
                TempData["toSubmit_Qns"] = questions;
                return RedirectToAction("CreateConfirm");
            }

            assignsViewBag_CreateQuestion();
            setupImageOptions_ViewBag();

            if(is_ImageOptionType)
            {
                byte optionNo = 0;
                for(byte i=0; i<Constants.OPTIONS_PER_QNS;i++)
                {
                    optionNo = (byte)(i + 1);
                    assignImageOptionsValue_ViewBag(optionNo, questions.getsOption_Value(optionNo), Constants.OPT_UPLOAD_IMAGE_STATE);
                }
            }

            return View(questions);

        }

        public ActionResult CreateConfirm()
        {
            Questions question = TempData["toSubmit_Qns"] as Questions;

            if(question !=null)
            {
                QuestionsViewModel question_options = new QuestionsViewModel();
                if(question.option_type.Equals(Constants.QNS_IMAGE_OPTION_TYPE))
                {
                    
                    question_options.option_1 = "<img src=\"" + Constants.IMG_PIC_UPLOAD_SRC + question.option_1
                        + "\" alt=\"Option 1 Image\" width=\"100\" height=\"100\" />";
                    question_options.option_2 = "<img src=\"" + Constants.IMG_PIC_UPLOAD_SRC + question.option_2
                        + "\" alt=\"Option 2 Image\" width=\"100\" height=\"100\" />";
                    question_options.option_3 = "<img src=\"" + Constants.IMG_PIC_UPLOAD_SRC + question.option_3
                        + "\" alt=\"Option 3 Image\" width=\"100\" height=\"100\" />";
                    question_options.option_4 = "<img src=\"" + Constants.IMG_PIC_UPLOAD_SRC + question.option_4
                        + "\" alt=\"Option 4 Image\" width=\"100\" height=\"100\" />";
                }
                else
                {
                    question_options.option_1 = question.option_1;
                    question_options.option_2 = question.option_2;
                    question_options.option_3 = question.option_3;
                    question_options.option_4 = question.option_4;
                }

                ViewBag.question_options = question_options;
                ViewBag.station_name = stationGateway.GetStationName_ByStationID(question.station_id);
                return View(question);
            }

            return RedirectToAction("Create");
            
        }

        [HttpPost, ActionName("CreateConfirm")]
        public ActionResult CreateConfirmed(Questions questions)
        {
            bool is_ImageOptionType = questions.option_type == Constants.QNS_IMAGE_OPTION_TYPE;
            KeyValuePair<string, string>[] imageValidation_Arr = new KeyValuePair<string, string>[Constants.OPTIONS_PER_QNS];
            string[] listOfFiles = null;
            bool modelState_Valid = true;

            if (is_ImageOptionType)
            {

HootHoot_CMS/Views/Questions/CreateConfirm.cshtml
@model HootHoot_CMS.Models.Questions

@{
    ViewBag.Title = "Create Confirm";
}

<h2>Confirm</h2>

<h4>Are you sure you want to create this question ?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.station_id)
        </dt>

        <dd>
            @Html.DisplayText("station_name")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.question_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.question_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.option_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.option_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.option_1)
        </dt>

        <dd>
            @Html.Raw(ViewBag.question_options.option_1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.option_2)
        </dt>

        <dd>
            @Html.Raw(ViewBag.question_options.option_2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.option_3)
        </dt>

        <dd>
            @Html.Raw(ViewBag.question_options.option_3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.option_4)
        </dt>

        <dd>
            @Html.Raw(ViewBag.question_options.option_4)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.correct_option)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.correct_option)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.question_has_hint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question_has_hint)
        </dd>

        @{
            if (Model.question_has_hint.Equals("YES"))
            {
                <dt>
                    @Html.DisplayNameFor(model => model.hint)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.hint)
                </dd>
            }

        }
       
        <dt>
            @Html.DisplayNameFor(model => model.answering_duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answering_duration)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.question_name, new { @class= "ignoreVal" })
        @Html.HiddenFor(model => model.question_type, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_type, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_1, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_2, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_3, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_4, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.correct_option, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.question_has_hint, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.hint, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.answering_duration, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.station_id, new { @class = "ignoreVal" })

        <div class="form-actions no-color">
            <input type="submit" value="Confirm" class="btn btn-default" /> |
        </div>
    }

    @using (Html.BeginForm("CreateBack","Questions"))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.question_name, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.question_type, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_type, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_1, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_2, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_3, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_4, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.correct_option, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.question_has_hint, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.hint, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.answering_duration, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.station_id, new { @class = "ignoreVal" })

        <div class="form-actions no-color">
            <input type="submit" value="Back" class="btn btn-default" />
        </div>
    }

</div>

HootHoot_CMS/Views/Questions/Delete.cshtml
@model HootHoot_CMS.Models.Questions

@{
    ViewBag.Title = "Delete Question";
}

<h2>Delete Question</h2>

<h4>Are you sure you want to delete this?</h4>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.station_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.station.station_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.question_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.question_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.option_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.option_type)
        </dd>

        @{
            if (Model.option_type.Equals(Constants.QNS_IMAGE_OPTION_TYPE))
            {
                <dt>
                    @Html.DisplayNameFor(model => model.option_1)
                </dt>
                <dd>
                    <img src=@Model.option_1 alt="Option 1 Image" width="100" height="100" />
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.option_2)
                </dt>
                <dd>
                    <img src=@Model.option_2 alt="Option 2 Image" width="100" height="100" />
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.option_3)
                </dt>
                <dd>
                    <img src=@Model.option_3 alt="Option 3 Image" width="100" height="100" />
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.option_4)
                </dt>
                <dd>
                    <img src=@Model.option_4 alt="Option 4 Image" width="100" height="100" />
                </dd>

            }
            else
            {
                <dt>
                    @Html.DisplayNameFor(model => model.option_1)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.option_1)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.option_2)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.option_2)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.option_3)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.option_3)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.option_4)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.option_4)
                </dd>

            }
        }

        
        <dt>
            @Html.DisplayNameFor(model => model.correct_option)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.correct_option)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.question_has_hint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question_has_hint)
        </dd>

        @{
            if (Model.question_has_hint.Equals("YES"))
            {
                <dt>
                    @Html.DisplayNameFor(model => model.hint)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.hint)
                </dd>
            }

        }

        <dt>
            @Html.DisplayNameFor(model => model.answering_duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answering_duration)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HootHoot_CMS/Views/Questions/EditConfirm.cshtml
@model HootHoot_CMS.Models.Questions

@{
    ViewBag.Title = "Edit Confirm";
}

<h2>Confirm</h2>

<h4>Are you sure you want to save these details for this question?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.station_id)
        </dt>

        <dd>
            @Html.DisplayText("station_name")
        </dd>


        <dd>
            @Html.DisplayFor(model => model.question_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.question_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.option_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.option_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.option_1)
        </dt>

        <dd>
            @Html.Raw(ViewBag.question_options.option_1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.option_2)
        </dt>

        <dd>
            @Html.Raw(ViewBag.question_options.option_2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.option_3)
        </dt>

        <dd>
            @Html.Raw(ViewBag.question_options.option_3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.option_4)
        </dt>

        <dd>
            @Html.Raw(ViewBag.question_options.option_4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.correct_option)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.correct_option)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.question_has_hint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question_has_hint)
        </dd>

        @{
            if (Model.question_has_hint.Equals("YES"))
            {
                <dt>
                    @Html.DisplayNameFor(model => model.hint)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.hint)
                </dd>
            }

        }

        <dt>
            @Html.DisplayNameFor(model => model.answering_duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answering_duration)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.question_name, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.question_type, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_type, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_1, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_2, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_3, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_4, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.correct_option, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.question_has_hint, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.hint, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.answering_duration, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.station_id, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.question_id, new { @class = "ignoreVal" })

        <div class="form-actions no-color">
            <input type="submit" value="Confirm" class="btn btn-default" /> |
        </div>
    }

    @using (Html.BeginForm("EditBack", "Questions"))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.question_name, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.question_type, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_type, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_1, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_2, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_3, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.option_4, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.correct_option, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.question_has_hint, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.hint, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.answering_duration, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.station_id, new { @class = "ignoreVal" })
        @Html.HiddenFor(model => model.question_id, new { @class = "ignoreVal" })

        <div class="form-actions no-color">
            <input type="submit" value="Back" class="btn btn-default" /> 
        </div>
    }
</div>